name: Hostinger_FTP_Deployment

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: ğŸš€ Hostinger'a GÃ¶nder
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Kodu Al
      uses: actions/checkout@v4

    - name: ğŸŸ¢ Node.js Kur
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: ğŸ”¨ BaÄŸÄ±mlÄ±lÄ±klarÄ± YÃ¼kle
      run: npm install 
    - name: ğŸ—ï¸ Projeyi Derle
      run: npm run build

    - name: ğŸ“‚ Hostinger FTP Transfer
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: ./public_html/ # Bu dizin Hostinger'da dosyalarÄ±n olduÄŸu yerdir